// <auto-generated />
namespace TomorrowsLunch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mealingredients_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mealingredients_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201609131204511_mealingredients_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
