// <auto-generated />
namespace TomorrowsLunch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration_quantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_quantity));
        
        string IMigrationMetadata.Id
        {
            get { return "201608261624092_migration_quantity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
