// <auto-generated />
namespace TommorowsLunch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class password_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(password_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201605032305286_password_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
